lobby:
    auto_accept: true
    accept_delay: 8
    avoid_autofill: true
    auto_start: true
    teammate:
    excess_queue_time: 35
    max_queue_time: 850 #stop queue reset once total time>850
champion_select:
    runes: !include 'runes.yaml'
    # accept_trades: false
    automate: true
    ban_delay: 25
    pick_delay: 15
    declare_delay: 9
    bottom:
        picks:
            - jinx
            - kaisa
            - vayne
            - jhin
            - missfortune
            - caitlyn
            - kogmaw

        bans:
            - amumu
            - senna
            - lux
            - leona
            - blitzcrank
            - brand
    middle:
        picks:
            - hwei
            - leblanc
            - lux
            - orianna
        bans:
            - xerath 
            - kassadin
            - yasuo
            - galio

    top:
        picks:
            - nasus
            - chogath
            - garen
            - vayne
        bans:
            - quinn
            - gwen
            - fiora
            - darius

    utility:
        picks:
            - sona
            - thresh
            - xreath
            - blitzcrank
        bans:
            - leona
            - lux
            - brand
            - zyra
            - morgana

    jungle:
        picks:
            - lilia
            - shyvana
            - amumu
            - rammus
        bans:
            - leesin
            - amumu
            - khazix
            - nocturne

post_game:
    honor_teammate: true
    skip_honor_delay: 10
    honor_types:
        heart: GGHeart
        cool: StayedCool
        caller: GreatShotcalling
    play_again: true
    play_again_delay: 15
