222:
    rune:
        name: "Jinx"
        current: true
        primaryStyleId: 8000,
        subStyleId: 8200
        selectedPerkIds:
            - 8005
            - 9101
            - 9104
            - 8014
            - 8139
            - 8138
            - 5008
            - 5008
            - 5002
            - 5002