222:
    primaryStyleId: 8000
    subStyleId: 8200
    selectedPerkIds:
        - 8005
        - 8009
        - 9103
        - 8014
        - 8233
        - 8236
        - 5005
        - 5008
        - 5001
    name: Jinx
    current: true
    