222:
    primaryStyleId: 8000
    subStyleId: 8200
    selectedPerkIds:
        - 8005
        - 718
        - 718
        - 8009
        - 918
        - 9104
        - 17
        - 20
        - 8014
        - 259
    name: Jinx
    current: true
    